In [166]:
# Add the dependencies.
import pandas as pd
import os

# Files to load
overview_to_load = os.path.join("Resources", "overview.csv")
performance_to_load = os.path.join("Resources", "performance.csv")


# Read the school data file and store it in a Pandas DataFrame.
overview_df = pd.read_csv(overview_to_load)
performance_df1 = pd.read_csv(performance_to_load)


performance_df1.sample(5)

,No.,Ticker,Performance (Week),Performance (Month),Performance (Quarter),Performance (Half Year),Performance (Year),Performance (YTD),Volatility (Week),Volatility (Month),Analyst Recom,Average Volume,Relative Volume,Price,Change,Volume
6411,6412,AMBP,0.21%,-4.74%,-20.00%,-6.32%,-1.63%,-7.31%,2.39%,3.07%,NaN,884.21,0.51,9.64,0.00%,0
5126,5127,XTNT,-7.32%,6.54%,-14.29%,-25.00%,2.24%,-4.69%,6.52%,5.63%,3.0,153.75,0.05,1.14,0.00%,380
5465,5466,BIOTU,2.11%,2.92%,2.42%,3.13%,NaN,0.03%,0.52%,0.32%,NaN,28.89,0.33,10.31,0.00%,0
246,247,USD,19.33%,51.71%,44.80%,106.23%,135.49%,99.13%,5.76%,3.60%,NaN,160.95,0.15,49.89,-3.11%,1170
802,803,BROS,-9.80%,31.80%,NaN,NaN,NaN,76.06%,8.23%,9.82%,NaN,3469.55,0.03,63.75,-1.29%,5951

In [173]:
new_column_order = ["Ticker", "Performance (Week)","Performance (YTD)", "Volatility (Month)","Average Volume","Performance (Half Year)"]
performance_df= performance_df1[new_column_order]
performance_df.head(5)

,Ticker,Performance (Week),Performance (YTD),Volatility (Month),Average Volume,Performance (Half Year)
0,ASLEW,-5.81%,510.22%,9.33%,154.86,380.93%
1,GPL,-14.36%,-55.00%,5.23%,1725.06,-51.41%
2,PRPL,-1.49%,-41.71%,4.62%,1064.06,-37.03%
3,POSH,0.45%,-75.83%,5.03%,1016.13,-43.97%
4,HSDT,-15.17%,-8.16%,5.24%,23.09,-20.10%

In [174]:
overview_df.sample(5)

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
1614,1615,KRBP,"Kiromic BioPharma, Inc.",Healthcare,Biotechnology,USA,21.10,NaN,2.86,-0.35%,175
2727,2728,DFE,WisdomTree Europe SmallCap Dividend Fund,Financial,Exchange Traded Fund,USA,NaN,NaN,75.89,0.00%,0
4425,4426,ECPG,"Encore Capital Group, Inc.",Financial,Mortgage Finance,USA,1764.72,5.98,59.08,0.00%,0
3384,3385,STE,STERIS plc,Healthcare,Medical Instruments & Supplies,Ireland,22605.89,81.35,228.99,0.00%,1
6254,6255,NUVL,"Nuvalent, Inc.",Healthcare,Biotechnology,USA,1317.26,NaN,26.85,0.00%,0

In [176]:
stocks_df = pd.merge (overview_df,performance_df,on=["Ticker","Ticker"], how = 'right')
stocks_df.sample(5)

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume,Performance (Week),Performance (YTD),Volatility (Month),Average Volume,Performance (Half Year)
943,953,SBET,SharpLink Gaming Ltd.,Consumer Cyclical,Gambling,USA,65.02,NaN,3.87,-1.02%,11394,4.27%,26.13%,7.52%,1363.51,-16.45%
3514,3497,SRV,The Cushing MLP & Infrastructure Total Return ...,Financial,Closed-End Fund - Equity,USA,77.27,NaN,35.39,0.00%,0,-1.42%,65.92%,1.61%,15.25,29.75%
6000,2718,NICK,"Nicholas Financial, Inc.",Financial,Credit Services,USA,154.20,11.01,12.00,0.00%,0,0.50%,43.20%,2.00%,10.73,16.50%
535,534,MILE,"Metromile, Inc.",Financial,Insurance - Property & Casualty,USA,430.62,NaN,3.19,-1.85%,50881,-0.31%,-79.10%,6.00%,3084.26,-54.67%
4675,2599,MKC,"McCormick & Company, Incorporated",Consumer Defensive,Packaged Foods,USA,21670.25,28.80,80.98,0.00%,14,-0.47%,-15.29%,1.44%,1062.88,-8.95%

In [177]:
total_companies =stocks_df["Company"].count()
print(f" There are {total_companies} in the US stock market")

 There are 8378 in the US stock market

In [46]:
sectors = len(stocks_df["Sector"].unique())
print(f" There are {sectors} sectors in the US stock market")

 There are 11 sectors in the US stock market

In [48]:
industries = len(stocks_df["Industry"].unique())
print(f" There are {industries} industries in the US stock market")

 There are 149 industries in the US stock market

In [71]:
total_market_cap = stocks_df["Market Cap"].sum()

print(f" The total Market cap of the US Stock market is {total_market_cap} usd")

 The total Market cap of the US Stock market is 70509138.30000001 usd

In [178]:
Big_market_cap=stocks_df[stocks_df["Market Cap"]>= 100000]
Big_market_cap.sample(5)

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume,Performance (Week),Performance (YTD),Volatility (Month),Average Volume,Performance (Half Year)
2999,5238,BRK-A,Berkshire Hathaway Inc.,Financial,Insurance - Diversified,USA,647520.00,6.34,431680.00,0.00%,0,-0.59%,24.11%,1.34%,1.33,1.50%
818,824,SHOP,Shopify Inc.,Technology,Software - Application,Canada,196844.01,57.96,1535.40,-1.25%,5420,5.30%,37.36%,3.71%,899.26,43.45%
7392,7386,DEO,Diageo plc,Consumer Defensive,Beverages - Wineries & Distilleries,United Kingdom,119892.72,33.29,204.35,0.21%,2148,0.60%,28.41%,0.74%,300.10,10.48%
1224,1382,CRM,"salesforce.com, inc.",Technology,Software - Application,USA,303986.55,122.85,307.98,-0.56%,14255,2.23%,39.18%,1.72%,5513.80,47.10%
1540,1566,AAPL,Apple Inc.,Technology,Consumer Electronics,USA,2469014.53,26.90,150.21,-0.39%,898039,0.53%,13.66%,1.46%,75826.93,22.84%

In [77]:
Big_market_cap_count = Big_market_cap["Company"].count()
print(f" There are {Big_market_cap_count} companies with a market cap over $100M USA today")

 There are 127 companies with a market cap over 100M USA today

In [179]:
high_market_cap_and_low_pe = stocks_df[(stocks_df["Market Cap"] >= 100000) & (stocks_df["P/E"] <= 50)]
high_market_cap_and_low_pe.sample(10)

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume,Performance (Week),Performance (YTD),Volatility (Month),Average Volume,Performance (Half Year)
7477,7472,CSCO,"Cisco Systems, Inc.",Technology,Communication Equipment,USA,242472.62,22.99,57.62,0.30%,104013,-0.31%,28.36%,1.52%,16044.12,11.32%
645,640,TSM,Taiwan Semiconductor Manufacturing Company Lim...,Technology,Semiconductors,Taiwan,566123.55,30.72,119.83,-1.60%,106585,6.72%,11.68%,1.96%,7895.03,12.54%
750,733,RDS-A,Royal Dutch Shell plc,Energy,Oil & Gas Integrated,Netherlands,176408.25,39.22,45.40,-1.39%,48338,1.41%,31.02%,1.65%,5597.28,16.26%
1111,1118,FB,"Meta Platforms, Inc.",Communication Services,Internet Content & Information,USA,918477.81,23.97,332.60,-0.83%,623267,2.22%,22.77%,2.46%,19259.24,10.85%
1685,1688,UNH,UnitedHealth Group Incorporated,Healthcare,Healthcare Plans,USA,438755.03,28.80,463.01,-0.29%,913,2.72%,32.41%,1.82%,2641.19,14.55%
6233,7165,IBM,International Business Machines Corporation,Technology,Information Technology Services,USA,105958.86,23.39,120.86,0.01%,16244,0.27%,0.51%,1.85%,5002.70,-10.46%
7718,7713,CMCSA,Comcast Corporation,Communication Services,Entertainment,USA,240249.06,17.31,54.12,0.69%,24104,2.11%,2.58%,2.15%,16388.36,-5.07%
864,848,RIO,Rio Tinto Group,Basic Materials,Other Industrial Metals & Mining,United Kingdom,101446.92,5.33,60.65,-1.22%,99752,-0.87%,-15.72%,1.47%,3507.99,-32.35%
2012,2052,MRK,"Merck & Co., Inc.",Healthcare,Drug Manufacturers - General,USA,232308.37,32.68,82.66,-0.07%,42697,-7.08%,6.05%,2.08%,14686.51,11.22%
232,233,AMD,"Advanced Micro Devices, Inc.",Technology,Semiconductors,USA,181366.69,46.11,144.13,-3.22%,1220796,16.68%,62.38%,4.14%,53183.05,99.52%

In [180]:
high_market_cap_and_low_pe_count = high_market_cap_and_low_pe["Company"].count()
high_market_cap_and_low_pe_count
print(f" There are {high_market_cap_and_low_pe_count} companies with a market cap over $100M USA and a P/E lower than 50 today")

 There are 93 companies with a market cap over $100M USA and a P/E lower than 50 today

In [181]:
mean_highMC_lowPE=high_market_cap_and_low_pe["Average Volume"].mean()
mean_highMC_lowPE

7603.306989247309

In [121]:
stocks_summary_df = pd.DataFrame(
    [{"Total companies":total_companies,
    "Sectors":sectors,
    "Industries":industries,
    "Total Market Cap":total_market_cap,
    "Companies MarketCap > $100M":Big_market_cap_count,
    "Companies MarketCap > $100M & PE<50":high_market_cap_and_low_pe_count,
    "Average dalily Volume ":mean_highMC_lowPE,},])

stocks_summary_df

,Total companies,Sectors,Industries,Total Market Cap,Companies MarketCap > $100M,Companies MarketCap > $100M & PE<50,Average dalily Volume
0,8378,11,149,70509138.3,127,93,7603.306989

In [182]:
stocks_summary_df = pd.DataFrame(
    [{"Total companies":total_companies,
    "Sectors":sectors,
    "Industries":industries,
    "Total Market Cap":total_market_cap,
    "Companies MarketCap > $100M ":Big_market_cap_count,
    "Companies MarketCap > $100M & PE<50 ":high_market_cap_and_low_pe_count,
    "Average dalily Volume":mean_highMC_lowPE,},])

stocks_summary_df["Total Market Cap"] = stocks_summary_df ["Total Market Cap"].map("${:,.0f}".format)
stocks_summary_df["Average dalily Volume"] = stocks_summary_df ["Average dalily Volume"].map("{:,.0f}".format)

pd.set_option('colheader_justify', 'center')
stocks_summary_df.style.set_properties(**{'text-align': 'center'})